name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Smoke tests
        run: |
          python - <<'PY'
          import json
          from api.main import app
          from fastapi.testclient import TestClient
          c = TestClient(app)
          assert c.get("/healthz").status_code == 200
          r = c.post("/v1/jobs", json={"type":"text.reverse","payload":{"text":"ci"}})
          jid = r.json()["job_id"]
          assert c.get(f"/v1/jobs/{jid}").status_code == 200
          print("OK")
          PY
